# Generated by Django 4.2.16 on 2024-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_tag_remove_task_due_date_remove_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, default='Test user', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(blank=True, default='Test user', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
